services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./src/api/Dockerfile
    ports:
      - 8080:80
    depends_on:
      - triton
    networks:
      - monitoring

  triton:
    container_name: triton
    image: nvcr.io/nvidia/tritonserver:24.09-py3
    ports:
      - 8000:8000  
      - 8001:8001   
      - 8002:8002   
    restart: always
    volumes:
      - ./triton/models:/models
    command: [
      "tritonserver",
      "--model-store=/models",
      "--allow-metrics=true",
      "--metrics-port=8002"
    ]
    networks:
      - monitoring
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: 1

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    restart: always
    depends_on:
      - triton
    networks:
      - monitoring

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_PROVISIONING_PATH=/etc/grafana/provisioning
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning  
    restart: always
    depends_on:
      - prometheus
    networks:
      - monitoring

volumes:
  prometheus_data:
  grafana_data:

networks:
  monitoring:
    driver: bridge