services:
  backend:
    container_name: backend
    build: 
      context: .
      dockerfile: ./src/api/Dockerfile
    ports:
      - 8080:80
    depends_on:
      - triton
    
  triton:
    container_name: triton
    image: nvcr.io/nvidia/tritonserver:24.09-py3
    ports:
      - 8000:8000 
      - 8001:8001  
      - 8002:8002  
    restart: always
    volumes:
      - ./triton/models:/models
    command: ["tritonserver", "--model-store=/models"]

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD} 
    restart: always

    